"""Definitions for the skill bank, keyed by slug.

House voice: deadpan, one to two sentences, specific. Say what the skill is
first; add the transfer angle only when it earns its place. No motivational
vocabulary, no "powerful" or "essential", numbers over adjectives.

These exist because a glossary entry that only lists the roles a skill unlocks
without saying what the skill *is* is not a definition. Anything missing here
falls back to the profile-derived line in build-skill-glossary.py, which should
be treated as a bug to fix, not a resting state.
"""

DEFS = {
    # ── Design and creative ──
    '3d-modeling': 'Building objects and spaces as geometry a computer can render, animate, or manufacture. The shared foundation under product design, games, film, and architectural visualization.',
    'rendering': 'Turning 3D geometry into a finished image by simulating how light behaves. The step that decides whether a design reads as convincing to a client.',
    'photoshop': "Adobe's raster image editor and the default tool for photo work, compositing, and texture painting. The most widely named creative software in postings.",
    'illustration': 'Drawing original imagery to a brief, by hand or digitally. Distinct from graphic design: illustration makes the picture, design arranges it.',
    'indesign': "Adobe's page-layout tool for multi-page documents, print and digital. The publishing half of graphic design, and still what magazines and reports are set in.",
    'after-effects': "Adobe's motion-graphics and compositing tool. Where static design becomes animation, and the standard skill in broadcast and social-video work.",
    'premiere': "Adobe's video editor for assembling footage, cutting, and finishing. Paired with After Effects across most video-production postings.",
    'video-editing': 'Cutting footage into a finished piece: pacing, sound, transitions, and colour. The craft transfers across marketing, journalism, and entertainment.',
    'videography': 'Shooting the footage: camera operation, framing, and coverage. The production half of video work, upstream of editing.',
    'photography': 'Making images with a camera to a brief, from product shots to editorial. Composition and lighting are the transferable part; the gear is not.',
    'photo-editing': 'Finishing images after the shoot: retouching, colour, and correction. The invisible labour that separates a usable frame from a published one.',
    'lighting-design': 'Shaping light to serve a scene, a stage, or a product shot. A discipline in film, theatre, and photography alike, and one of the least outsourceable creative skills.',
    'audio-mixing': 'Balancing recorded audio into a finished track: levels, EQ, effects, and mastering. The post-production half of sound work.',
    'motion-design': 'Designing things that move — titles, explainers, interface animation. Sits between graphic design and animation and is heavily in demand in marketing.',
    'previs': 'Blocking out a sequence cheaply before it is made properly, through storyboards or rough 3D. It is how expensive productions avoid discovering problems on set.',
    'texturing': 'Painting the surface properties of a 3D model so it reads as metal, cloth, or skin. The step that makes geometry look like a thing.',
    'character-rigging': 'Building the skeleton and controls that let an animator move a 3D character. Technical, unglamorous, and the bottleneck on most animation pipelines.',
    'lookdev': 'Developing the final visual character of an asset or shot: shaders, materials, and how it responds to light. Where technical and artistic judgment meet.',
    'generative-design': 'Letting an algorithm produce and test many design options against stated goals rather than drawing one by hand. The computational-design method, used in architecture and product engineering.',
    'visual-design': 'The craft of how an interface or artefact looks: typography, colour, spacing, hierarchy. Distinct from UX, which is about how it works.',
    'typography': 'Setting type so it is readable and says the right thing before a word is read. The most transferable design skill and the one most often skipped.',
    'branding': 'Building the identity a company is recognized by: mark, voice, and the rules that keep it consistent. Strategy as much as craft.',
    'design-thinking': 'A structured approach to problems: understand the user, frame the problem, prototype, test. A vocabulary hiring managers screen for in design and product roles.',
    'design-systems': 'The shared component library and rules that keep a product visually consistent at scale. The infrastructure of design, and increasingly its own job.',
    'interaction-design': 'Designing what happens when someone acts: states, transitions, feedback, and flow. The behavioural half of interface work.',
    'wireframing': 'Sketching an interface in low fidelity to settle structure before appearance. Fast, disposable, and the cheapest place to be wrong.',
    'usability-testing': 'Watching real people attempt real tasks with a product and recording where they fail. The check on designer intuition.',
    'user-research': 'Learning what users actually need through interviews, observation, and analysis, rather than assuming. Upstream of every other design decision.',
    'service-design': 'Designing the whole journey across touchpoints, staff, and systems, not just the screen. Common in public sector, health, and finance.',
    'accessibility': 'Building products usable by people with disabilities, to standards like WCAG. Legally required in many markets and a defensible specialization.',
    'set-design': 'Designing and building the physical environment of a production, for stage, film, or events. Architecture with a deadline and no permanence.',
    'exhibit-design': 'Designing spaces that explain something: museums, showrooms, trade stands. Combines spatial design with narrative and graphics.',
    'furniture-design': 'Designing objects people sit on, work at, and store things in, with manufacture in mind. Sits between industrial design and interiors.',
    'space-planning': 'Working out how much space a function needs and how the pieces fit together. The first move in interior and workplace design.',
    'ffe': 'Furniture, fixtures, and equipment: specifying and procuring everything in a space that is not structure. The commercial half of interior design.',
    'creative-coding': 'Writing code to make visual or interactive artefacts rather than software products. The bridge from design into installations and generative work.',
    'sketchup': 'A fast, forgiving 3D modeller widely used for early architectural and interior massing. Low ceiling, very low floor, which is why it is everywhere.',
    'figma': 'The browser-based interface design tool that became the industry default, largely because several people can work in one file at once.',
    'unity': 'A real-time 3D engine used for games, simulation, AR/VR, and increasingly architectural and automotive visualization.',
    'unreal': "Epic's real-time engine, dominant in high-fidelity games and now in virtual production and architectural visualization.",

    # ── Architecture, engineering, construction ──
    'bim': 'Building Information Modeling: designing buildings as data-rich 3D models rather than drawings, so quantities, clashes, and schedules come from the model itself.',
    'cad-drafting': 'Producing the dimensioned technical drawings a thing gets built from. The documentation discipline underneath architecture and engineering.',
    'cad-mechanical': 'Parametric 3D modelling of parts and assemblies for manufacture, with tolerances and fits. The product-engineering counterpart to building CAD.',
    'construction-documents': 'The drawing and specification set a building is actually built from. Producing them is most of what junior architectural work is.',
    'construction-administration': 'Running the architect or engineer side during construction: RFIs, submittals, site visits, and change orders. Where drawings meet reality.',
    'blueprint-reading': 'Reading technical drawings accurately enough to build from them. A baseline requirement across trades, fabrication, and field engineering.',
    'building-codes': 'Knowing the regulations a building must satisfy for occupancy, egress, fire, and accessibility. The constraint set every design decision is checked against.',
    'clash-detection': 'Finding where structure, ducts, pipes, and cable trays occupy the same space before anyone builds it. The main commercial argument for BIM.',
    'cost-estimating': 'Pricing work from drawings: quantities, rates, and contingency. The skill that decides whether a project proceeds.',
    'structural-analysis': 'Calculating how loads move through a structure and whether the members can carry them. The core of structural engineering practice.',
    'steel-design': 'Designing structures in steel: member sizing, connections, and the relevant code. Fabrication-led, and detail-heavy at the connections.',
    'fea': 'Finite Element Analysis: simulating stress and deflection by breaking a structure into a mesh of small elements. The analysis behind a structural or mechanical claim.',
    'mep': 'Mechanical, electrical, and plumbing engineering, the building systems that sit alongside architecture on every project.',
    'hvac-systems': 'Heating, ventilation, and air conditioning as designed systems: loads, ductwork, and equipment selection. The largest energy consumer in most buildings.',
    'electrical-systems': 'Designing building power and lighting distribution: loads, panels, and code compliance. The design-side counterpart to electrical installation.',
    'electrical-wiring': 'Installing and terminating electrical work to code: conduit, panels, and circuits. Licensed, hands-on, and not remotely deliverable.',
    'plumbing': 'Installing and maintaining water supply, drainage, and gas systems. A licensed trade with steady demand and no remote option.',
    'refrigeration': 'Servicing systems that move heat: chillers, compressors, and refrigerant handling, which is certificated work. The technical core of HVAC field service.',
    'carpentry-framing': 'Building the structural skeleton of a timber building: walls, floors, and roof. Fast, physical, and measured in tolerances of millimetres.',
    'finish-carpentry': 'The visible woodwork: trim, cabinetry, and joinery, where the tolerance is what the eye can see. The high-skill end of the carpentry trade.',
    'welding-fabrication': 'Joining and forming metal to a drawing, by process and position. Certificated per process, and the certification is what employers screen for.',
    'hand-power-tools': 'Competent, safe use of the tools a trade runs on. Assumed rather than taught in most trade postings.',
    'preventive-maintenance': 'Servicing equipment on a schedule so it does not fail unscheduled. The discipline that separates a maintained plant from a firefighting one.',
    'osha-safety': 'Site safety practice and the regulations behind it: hazard control, fall protection, lockout/tagout. Often a hard requirement before anyone steps on site.',
    'safety': 'Identifying hazards and controlling them before they cause harm. A named responsibility in industrial, clinical, and construction roles.',
    'rigging-materials': 'Moving heavy loads safely: slings, cranes, forklifts, and load securement. Certificated, and unforgiving of improvisation.',
    'solar-pv': 'Designing and installing photovoltaic systems: array layout, racking, and inverters. One of the faster-growing trades in our data.',
    'leed': 'The most widely used green-building certification, run by the US Green Building Council. A credential that signals sustainability fluency in AEC postings.',
    'energy-modeling': 'Simulating how much energy a building will use before it is built, to test design decisions and prove code compliance.',
    'digital-twin': 'A live digital model of a physical asset, fed by sensor data, used to monitor and predict its behaviour. The operations-side argument for BIM.',
    'point-cloud': 'The dense set of measured 3D points a laser scanner produces, and the workflows for turning it into usable geometry. How existing buildings get surveyed.',
    'gis': 'Geographic Information Systems: analysing and mapping anything with a location. Spans planning, utilities, logistics, environment, and public health.',
    'zoning': 'The land-use rules that dictate what may be built where, and at what size. The first constraint on any development.',
    'urban-design': 'Designing the space between buildings: streets, blocks, and public realm. Sits between architecture and city planning.',
    'transportation-planning': 'Planning how people and goods move through a place: networks, demand modelling, and transit. Heavily public-sector.',
    'community-engagement': 'Running the consultation that lets affected people shape a plan. A required step in most public projects and a distinct professional skill.',
    'policy-analysis': 'Assessing what a policy would actually do — costs, beneficiaries, second-order effects — and writing it up for decision-makers.',
    'primavera': "Oracle's Primavera P6, the scheduling tool of large construction and engineering programmes. Where critical-path planning lives on major projects.",
    'navisworks': "Autodesk's model-review and clash-detection tool, used to combine models from every discipline and check them against each other.",
    'civil-3d': "Autodesk's civil engineering design tool for grading, corridors, and site work. The land-development counterpart to Revit.",
    'arcgis': "Esri's GIS platform, the dominant professional toolset for spatial analysis and mapping.",

    # ── Software and data ──
    'javascript': 'The language every web browser runs. Unavoidable in front-end work and common on the server through Node.',
    'typescript': 'JavaScript with a type system bolted on, catching a class of bugs before the code runs. Now the default choice for new front-end and Node projects.',
    'react': 'The dominant JavaScript library for building user interfaces from composable components. The most-requested front-end skill in our data.',
    'vue': 'A JavaScript framework for building interfaces, lighter to adopt than React and popular in Europe and Asia.',
    'angular': "Google's full-featured front-end framework, opinionated and common in large enterprise applications.",
    'nodejs': 'JavaScript running on the server, which lets one language cover both ends of a web application.',
    'html-css': 'The markup and styling that every web page is made of. The floor of front-end work, and the part that decides whether a site is usable.',
    'full-stack': 'Working across both the interface and the server and database behind it. Valued at smaller companies, where one person owns a whole feature.',
    'java': 'A mature, statically typed language that runs most large enterprise back-ends and Android applications. Unfashionable and extremely well paid.',
    'csharp': "Microsoft's general-purpose language, standard across enterprise .NET back-ends and Unity game development.",
    'cpp': 'A systems language for work where performance and memory control matter: engines, trading, embedded, and graphics.',
    'swift': "Apple's language for iOS and macOS applications. The entry requirement for native Apple development.",
    'scala': 'A JVM language combining functional and object-oriented styles, most often encountered in large-scale data processing.',
    'sap': "The enterprise resource planning system large companies run their operations on. SAP fluency is a durable, well-paid specialization of its own.",
    'microservices': 'Building a system as many small independently deployed services instead of one large application. An architectural choice with real operational cost.',
    'system-design': 'Deciding how the pieces of a large system fit together: data flow, storage, failure modes, and scale. The skill senior engineering interviews test for.',
    'site-reliability': 'Keeping production systems available and fast, and automating the work that would otherwise be manual toil. Engineering applied to operations.',
    'docker': 'Packaging software with its dependencies into containers so it runs the same everywhere. The unit modern deployment is built on.',
    'kubernetes': 'The system that runs and scales containers across a fleet of machines. Powerful, complicated, and a well-paid specialization.',
    'terraform': 'Declaring cloud infrastructure as code so environments are reproducible and reviewable rather than hand-clicked.',
    'cicd': 'The automated pipeline that tests and ships code on every change. What makes frequent, low-drama releases possible.',
    'linux': 'The operating system nearly all servers run. Comfort at its command line is assumed in backend, DevOps, and security work.',
    'git': 'The version control system essentially all software is tracked in. Assumed rather than requested, and still worth knowing properly.',
    'networking': 'How machines actually talk: addressing, routing, DNS, and firewalls. The layer everything else quietly depends on.',
    'qa-testing': 'Verifying software behaves as intended, by hand and through automation. The discipline that decides what "done" means.',
    'gcp': "Google Cloud Platform, the third major cloud, strongest in data and machine-learning workloads.",
    'jira': "Atlassian's issue tracker, where a large share of software work is planned and recorded.",
    'sql': 'The query language for relational databases: how you pull, filter, and join data that lives in tables. The baseline data skill.',
    'nosql': 'Databases that do not use the relational table model, for data that is document-shaped, huge, or fast-changing.',
    'etl': 'Extract, transform, load: moving data out of source systems, reshaping it, and landing it somewhere analysts can use. The core of data engineering.',
    'data-engineering': 'Building and running the pipelines and warehouses analysts depend on. The plumbing that decides whether analysis is possible at all.',
    'data-modeling': 'Designing how data is structured and related so it can be queried sensibly. Get it wrong and every downstream query is painful.',
    'data-governance': 'The rules and controls over who can use which data and how: quality, lineage, privacy, and retention. Increasingly a compliance requirement.',
    'dbt': 'A tool for building transformation logic in the warehouse as version-controlled, tested SQL. It brought software practice to analytics.',
    'airflow': 'A scheduler for data pipelines: defining tasks, dependencies, and retries in code. The workhorse orchestrator of data engineering.',
    'looker': "Google's business-intelligence platform, which models metrics centrally so different teams get the same number.",
    'tableau': 'A business-intelligence tool for building interactive dashboards from data. Widely deployed and often the analyst tool a job is defined around.',
    'power-bi': "Microsoft's business-intelligence tool, dominant wherever the rest of the Microsoft stack is already in place.",
    'statistics': 'Reasoning about data under uncertainty: distributions, significance, and how confident a number deserves to be. The discipline under honest analysis.',
    'ab-testing': 'Running controlled experiments to establish whether a change actually caused an effect. The difference between a decision and a guess.',
    'market-research': 'Structured investigation of a market: who buys, why, and what they would pay. Mixes survey design, interviews, and analysis.',
    'forecasting': 'Projecting future values from history and assumptions, and being explicit about the assumptions. Central to finance, planning, and operations.',
    'deep-learning': 'Machine learning with many-layered neural networks, the approach behind modern vision and language systems.',
    'computer-vision': 'Getting machines to interpret images and video: detection, segmentation, and tracking. Used well beyond tech, in agriculture, medicine, and manufacturing.',
    'nlp': 'Natural language processing: getting machines to work with human language. Largely absorbed by large language models, but the fundamentals still hire.',
    'mlops': 'Running machine-learning models in production reliably: deployment, monitoring, retraining, and rollback. What separates a working model from a demo.',
    'rag': 'Retrieval-augmented generation: letting a language model answer from a specific document set by fetching relevant passages first. A standard AI-engineering pattern.',
    'fine-tuning': 'Further training a general model on your own data so it behaves the way a specific task needs. The main alternative to prompting.',
    'prompt-engineering': 'Getting reliable output from a language model by structuring the instruction and context. Newer than it sounds and less mystical than claimed.',
    'model-evaluation': 'Measuring whether a model is actually good: benchmarks, error analysis, and the failure cases that matter. The unglamorous half of AI work.',
    'sagemaker': "Amazon's managed platform for training and deploying machine-learning models on AWS.",

    # ── Product, marketing, sales, operations ──
    'saas': 'Software sold as an ongoing subscription rather than a licence. The business model that shapes how most modern software companies hire and operate.',
    'go-to-market': 'The plan for how a product reaches buyers: segments, pricing, channels, and launch. Where product and commercial thinking meet.',
    'product-marketing': 'Positioning a product and equipping the people who sell it: messaging, launches, and competitive material. Sits between product and sales.',
    'content-marketing': 'Earning attention by publishing something worth reading rather than buying ad space. Slow, compounding, and hard to fake.',
    'copywriting': 'Writing to make someone act: pages, ads, emails. Judged on outcome rather than elegance.',
    'seo': 'Shaping content and sites so they surface in search results. Increasingly a matter of being cited inside AI answers rather than ranked as a link.',
    'sem': 'Buying search advertising and managing the spend against return. The paid counterpart to SEO.',
    'semrush': 'A search and competitive analytics platform, used to size keyword demand and track visibility against rivals.',
    'google-analytics': "Google's web analytics platform, the default record of who visited and what they did.",
    'email-marketing': 'Owning the one channel that is not rented from a platform: lists, sequences, and deliverability.',
    'social-media': 'Building and holding an audience on platforms you do not control. Part content, part community, part analytics.',
    'demand-generation': 'Creating measurable commercial demand through campaigns and content, and tracking it to pipeline. The quantitative end of marketing.',
    'sales': 'Finding buyers, understanding their problem, and closing. The most measurable job in most companies.',
    'sales-enablement': 'Equipping salespeople to sell: training, material, and process. A common bridge from selling into management.',
    'account-management': 'Keeping and growing existing customers after the sale. Retention economics make it as valuable as new business.',
    'business-development': 'Opening new markets, partnerships, and channels rather than working an existing pipeline. Strategy with a quota attached.',
    'b2b': 'Selling to businesses rather than consumers: longer cycles, several stakeholders, and procurement. A different discipline from B2C.',
    'crm': 'The system of record for customer relationships and pipeline. Fluency in one transfers readily to the others.',
    'revenue-operations': 'Owning the systems, data, and process behind marketing, sales, and success as one pipeline. A fast-growing function.',
    'negotiation': 'Reaching agreement where interests differ, without burning the relationship. Transfers into sales, procurement, law, and management.',
    'presentation': 'Standing up and making an argument land, to a room or a camera. Consistently undervalued on resumes and consistently decisive in promotion.',
    'event-planning': 'Running events end to end: logistics, vendors, budget, and the day itself. Project management with an immovable deadline.',
    'operations': 'Making the day-to-day machinery of a business run: process, capacity, and exceptions. The function that absorbs everything nobody else owns.',
    'quality-control': 'Checking that output meets specification, and acting when it does not. Formalized in manufacturing, clinical, and food work.',
    'inventory-management': 'Knowing what stock exists, where, and what to reorder. Ties up capital when wrong in either direction.',
    'shipping-receiving': 'Moving goods in and out accurately: documentation, freight, and dispatch. The physical edge of the supply chain.',
    'vendor-management': 'Selecting suppliers and holding them to what was agreed: terms, performance, and escalation.',
    'facilities-operations': 'Keeping a building running for its occupants: maintenance, contractors, compliance, and cost.',
    'program-management': 'Running several related projects toward one outcome, including the dependencies between them. A step up from project management in scope.',
    'change-management': 'Getting an organization to actually adopt a change, rather than just announcing it. The human half of every transformation.',
    'people-management': 'Being accountable for other people: hiring, direction, feedback, and performance. A different job from the one that earned the promotion.',
    'recruiting': 'Finding, assessing, and closing candidates. Part sales, part judgment, and measured on both speed and quality.',
    'hr-operations': 'The machinery of employment: onboarding, records, payroll interfaces, and policy. Unglamorous and legally consequential.',
    'risk-management': 'Identifying what could go wrong, sizing it, and deciding what to do about it. Formalized in finance, insurance, and safety-critical work.',
    'compliance': 'Making sure an organization meets the rules that bind it, and proving it. Grows with regulation and rarely shrinks.',
    'contracts': 'Drafting, reviewing, and administering the agreements that govern commercial relationships. Where commercial intent becomes enforceable.',
    'contract-review': 'Reading agreements for risk and negotiating the terms that matter. The most common commercial legal task.',

    # ── Finance and legal ──
    'financial-modeling': 'Building a spreadsheet model of a business or deal to test assumptions and value outcomes. The core analytical craft of finance.',
    'budgeting': 'Planning what will be spent, by whom, against what outcome, and holding the line. Every manager does some version of it.',
    'audit': 'Independently checking that financial records represent reality, to a standard. Regulated, methodical, and a common route into finance.',
    'tax': 'Applying tax law to transactions and filings. Rules-heavy, jurisdiction-specific, and consistently in demand.',
    'accounts-payable': 'Processing what the business owes and what it is owed, accurately and on time. The transactional core of bookkeeping.',
    'reconciliation': 'Proving two records agree — ledger against bank, system against system — and explaining the difference. The month-end discipline.',
    'payroll': 'Paying people correctly and on time, with the right deductions. Highly regulated and unforgiving of error.',
    'underwriting': 'Deciding which risks to accept and at what price. The judgment at the centre of insurance and lending.',
    'claims-handling': 'Assessing and settling insurance claims: validity, value, and the customer through it. The moment an insurance product is actually tested.',
    'bloomberg': 'The Bloomberg Terminal, the market data and analytics system finance runs on. Fluency is a screening credential in trading and research.',
    'escrow-closing': 'Completing a property transaction: title, funds, and documents. The regulated final step of any real-estate deal.',
    'real-estate-listing': 'Winning and marketing a property listing: pricing from comparables, presentation, and buyer handling.',
    'legal-research': 'Finding the law that governs a question and stating it accurately. The foundational lawyer and paralegal skill.',
    'litigation-support': 'Preparing a case for hearing: evidence, disclosure, bundles, and deadlines. Where most paralegal work sits.',
    'docketing': 'Tracking court deadlines and filings so nothing is missed. Administratively dull and catastrophic to get wrong.',
    'ip-prosecution': 'Securing patents and trademarks: drafting, filing, and arguing with the examiner. Technical, and usually requires a science background.',
    'law-enforcement': 'Policing work: patrol, response, investigation, and evidence. Licensed and jurisdiction-bound.',
    'criminal-investigation': 'Building a case from evidence, interviews, and records to an evidential standard.',
    'public-safety': 'The coordinated function that keeps a population safe: emergency response, prevention, and preparedness.',
    'emergency-response': 'Acting effectively in the first minutes of an incident, under a defined command structure.',
    'firearms': 'Certified competence in the safe handling and use of firearms. Required in specific law-enforcement, military, and security roles.',
    'aviation-ops': 'Running flight operations on the ground and in the air: scheduling, dispatch, compliance, and safety.',
    'flight-operations': 'Planning and executing flights to regulation: routes, weather, weight and balance, and crew procedure.',
    'cabin-safety': 'Managing passenger safety in flight: procedure, equipment, and emergency response. The actual job under the service role.',

    # ── Health and clinical ──
    'clinical': 'Direct professional work with patients under a clinical standard of care. The common core beneath most health occupations.',
    'ehr': 'Electronic health records: the systems clinical work is documented and billed in. Fluency in one is a named requirement in most clinical postings.',
    'clinical-documentation': 'Recording care accurately and to standard, because it drives continuity, billing, and legal defence.',
    'medical-terminology': 'The vocabulary of anatomy, procedures, and conditions. The entry requirement for every administrative and clinical health role.',
    'triage': 'Sorting patients by urgency so the sickest are seen first. Rapid, consequential judgment under load.',
    'vital-signs': 'Measuring and interpreting the basic indicators of physiological state. The first thing taken and the first thing to change.',
    'medication-administration': 'Giving the right drug, dose, and route to the right patient, and recording it. Heavily protocolized because the failure modes are severe.',
    'treatment-planning': 'Setting out what care a patient will receive, in what order, toward what goal. Shared across clinical, dental, and therapy work.',
    'rehabilitation': 'Restoring function after injury, surgery, or illness through structured therapy and progressive exercise.',
    'manual-therapy': 'Hands-on treatment of joints and soft tissue to restore movement and reduce pain. The physical craft of physiotherapy.',
    'emergency-care': 'Stabilizing and treating acutely unwell or injured patients, often before hospital. Protocol-driven and time-critical.',
    'cpr-bls': 'Basic life support: chest compressions, ventilation, and defibrillation. A certification requirement across almost all clinical roles.',
    'infection-control': 'Preventing the spread of infection through technique, sterilization, and protocol. Every clinical setting has a named standard.',
    'local-anesthesia': 'Administering local anaesthetic safely, a certificated skill in dental and minor-procedure practice.',
    'periodontal-care': 'Treating the gums and supporting structures of the teeth: scaling, root planing, and maintenance. The clinical core of dental hygiene.',
    'radiography': 'Producing diagnostic images safely, managing exposure and positioning. Licensed, because the dose is real.',
    'case-management': 'Coordinating the services one person needs across providers and agencies, and following through. Central to social work and complex care.',
    'health-education': 'Teaching patients and communities to manage and prevent illness, in language they can act on.',
    'mental-health': 'Assessment and support of psychological wellbeing, from screening through therapeutic work. Demand consistently exceeds supply.',
    'telehealth': 'Delivering care remotely by video or phone, including the assessment limits that come with it. Now a standard modality rather than an experiment.',
    'perfusion': 'Running the heart-lung machine during cardiac surgery, maintaining circulation while the heart is stopped. Small profession, very high stakes.',
    'gmp': 'Good Manufacturing Practice: the regulated quality system pharmaceutical and food production must operate under, with documentation to prove it.',
    'lab-techniques': 'The bench methods of analysis — chromatography, spectroscopy, assays — and the discipline to run them reproducibly.',
    'process-safety': 'Preventing catastrophic release in facilities handling hazardous materials, through structured hazard analysis. Distinct from personal safety.',
    'process-engineering': 'Designing and improving the processes that convert inputs into product at industrial scale: mass balance, unit operations, and yield.',

    # ── Education and information ──
    'curriculum': 'Deciding what gets taught, in what order, toward what outcome. The design layer above individual lessons.',
    'lesson-planning': 'Designing a single session so it has a purpose, a shape, and evidence that it worked.',
    'classroom-management': 'Establishing the conditions where learning is possible: routine, attention, and behaviour. The skill that decides whether the teaching lands.',
    'behavior-management': 'Responding to challenging behaviour with strategy rather than escalation. Increasingly its own specialization in schools.',
    'differentiated-instruction': 'Teaching one class of very different learners without teaching to the middle. The hardest routine demand of the job.',
    'special-education': 'Teaching students with additional needs, including the legal plans that govern it. Its own qualification and consistently short-staffed.',
    'early-childhood': 'Working with children before formal schooling, where development matters more than curriculum.',
    'literacy-instruction': 'Teaching reading explicitly, through phonics and structured practice. The most consequential thing a primary school does.',
    'esl-teaching': 'Teaching English to speakers of other languages, in classrooms or online. Portable, credentialed, and genuinely global.',
    'tutoring': 'Teaching one to one, diagnosing the individual gap rather than delivering a plan. The most direct form of teaching work.',
    'assessment': 'Measuring what someone has actually learned, and designing the instrument that measures it fairly.',
    'instructional-design': 'Designing learning experiences for adults, usually corporate and usually digital. The most common landing spot for teachers leaving the classroom.',
    'research': 'Investigating a question systematically and reporting what the evidence supports. The transferable core of academic work.',
    'technical-writing': 'Explaining complex systems precisely to the person who has to use them: documentation, procedures, and references.',
    'translation': 'Rendering meaning from one language into another so it reads as though written in the target. Not word substitution.',
    'localization': 'Adapting a product for another market: language, format, currency, and cultural fit. Broader than translation, and usually engineering-adjacent.',
    'fact-checking': 'Verifying claims against primary sources before publication. The function that makes a publication trustworthy.',
    'cataloging': 'Describing and classifying items so they can be found again. The intellectual infrastructure of libraries and archives.',
    'information-literacy': 'Teaching people to find, evaluate, and use sources well. Increasingly the point of a library.',

    # ── Food, hospitality, retail ──
    'food-safety': 'Preventing foodborne illness through temperature control, hygiene, and documented procedure. Legally mandated and inspected.',
    'menu-development': 'Designing what a kitchen serves against cost, capability, season, and identity. Creative work with a margin attached.',
    'line-cooking': 'Executing dishes to standard at service speed, on a station, under pressure. The craft the whole kitchen is built on.',
    'kitchen-management': 'Running the back of house: people, orders, stock, and standards, through service.',
    'baking-pastry': 'The precise, chemistry-led side of the kitchen, where a recipe is a formula and timing is not negotiable.',
    'food-cost': 'Controlling what ingredients cost relative to what is charged: portioning, waste, and yield. Where a restaurant makes or loses money.',
    'catering': 'Producing and serving food away from a fixed kitchen, at volume and to a schedule.',
    'wine-service': 'Selecting, storing, and serving wine, and guiding a guest to a choice. Certificated, and one of the few hospitality skills with a formal ladder.',
    'brewing': 'Producing beer at commercial scale: recipe, fermentation control, and consistency batch to batch. Applied microbiology with a product.',

    'hipaa': 'The US law governing the privacy and security of health information, and the handling rules that follow from it. Named in clinical, health-tech, and health-adjacent administrative postings.',
    'plc': 'Programmable Logic Controller: the ruggedized industrial computer that runs machinery and process automation. The boundary marker between building electrical work and industrial controls.',
}

# Hospitality, property, library and airspace vocabulary — added 2026-07-31 with the
# nine skills that lifted hotel-manager from a four-skill profile to nine. See
# docs/31-corpus-quality.md.
DEFS.update({
    'guest-relations': 'Handling guests as people rather than bookings: recovery when something has gone wrong, and the satisfaction scores that follow. The measured half of hospitality.',
    'front-office': 'The desk a guest actually meets — arrivals, departures, and the overnight audit that reconciles the day. In banking the same words mean the trading floor, which is a different job.',
    'housekeeping': 'Room turnover at volume: attendants, linen, and the standards that survive an inspection. Not the same word trades postings use for tidying a workshop.',
    'hotel-operations': 'Running the property end to end — rooms, staffing, occupancy, and the brand standards an owner audits against.',
    'food-beverage': 'Running the kitchens, bars, and banqueting a venue sells. Distinct from being a supplier who sells into the food and beverage trade.',
    'revenue-management': 'Pricing perishable inventory — a room tonight is worthless tomorrow. Rate strategy, occupancy forecasting, and yield.',
    'property-management': 'Running buildings on behalf of an owner: tenancies, leases, rent, and the repairs in between. The recurring-income side of real estate.',
    'library-services': 'The operating layer of a library — circulation, interlibrary loan, reader guidance, and the systems underneath. Distinct from cataloguing the collection.',
    'air-traffic-control': 'Separating aircraft in a defined block of airspace. Licensed, rated per facility, and one of the few jobs with no informal route in.',
})
